# Generated by Django 5.0.6 on 2024-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuserauth", "0002_alter_customusermodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
